server {
    listen 8080;
    server_name a;
    root ./www;
    location / { allowed_methods GET; }
}
server {
    listen 8080;
    server_name b;
    root ./www;
    location / { allowed_methods GET; }
}
